<?php

namespace App\Entities\Product\Repository;

use Cboy868\Repositories\Eloquent\SoftDeleteRepository;

/**
 * Class AttributeCategoryRepository
 * @package App\Entities\Product\Repository
 *
 * @link http://www.zhuo-xun.com/
 * @copyright Copyright (c) 2018 zhuoxun Software LLC
 *
 */
class AttributeCategoryRepository extends SoftDeleteRepository
{
    function model()
    {
        return 'App\Entities\Product\AttributeCategory';
    }


    public function create(array $data)
    {
        $model = parent::create($data); // TODO: Change the autogenerated stub

        $this->afterCreate($model);

        return $model;
    }

    public function afterCreate($model)
    {
        $model->is_leaf = 1;
        if ($model->pid == 0) {
            $model->level = 1;
            $model->code = $model->id;
        } else {
            $parent = $model->getParent();
            $parent->is_leaf = 0;
            $parent->save();

            $model->level = $parent->level + 1;
            $model->code = $parent->code . '.' . $model->id;
        }
        $model->save();

    }
}